In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import unicodedata

In [2]:
df = pd.read_excel("../../crawl_data/data/data_tv.xlsx")

In [3]:
df.head()

,id,sku,name,url_key,url_path,type,author_name,book_cover,brand_name,short_description,...,badges_new_3_promotions_0_icon_height,badges_new_3_promotions_0_icon_width,badges_new_3_promotions_0_text,visible_impression_info_amplitude_ineligible_coupon_rule_id,badges_new_2_icon,badges_new_2_icon_height,badges_new_2_icon_width,badges_new_4_icon,badges_new_4_icon_height,badges_new_4_icon_width
0,278220734,2004742899164,[NEW 2026 TV Series] Smart Tivi Xiaomi TV A Pr...,new-2026-tv-series-smart-tivi-xiaomi-tv-a-pro-...,new-2026-tv-series-smart-tivi-xiaomi-tv-a-pro-...,NaN,NaN,NaN,Xiaomi,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,278138258,5502954751332,Smart Tivi LG AI 4K 55 Inch 55UA8450PSA- Hàng ...,smart-tivi-lg-ai-4k-55-inch-55ua8450psa-hang-c...,smart-tivi-lg-ai-4k-55-inch-55ua8450psa-hang-c...,NaN,NaN,NaN,LG,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,278138206,6189447443433,Smart Tivi LG AI 4K 65 Inch 65UA8450PSA- Hàng ...,smart-tivi-lg-ai-4k-65-inch-65ua8450psa-hang-c...,smart-tivi-lg-ai-4k-65-inch-65ua8450psa-hang-c...,NaN,NaN,NaN,LG,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,278077419,1516540466887,Google Tivi Xiaomi A 2026 4K 55 inch L55MB-ASE...,google-tivi-xiaomi-a-2026-4k-55-inch-l55mb-ase...,google-tivi-xiaomi-a-2026-4k-55-inch-l55mb-ase...,NaN,NaN,NaN,Xiaomi,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,278077327,2768528301218,Google Tivi Xiaomi A 2026 4K 43 inch L43MB-AUS...,google-tivi-xiaomi-a-2026-4k-43-inch-l43mb-aus...,google-tivi-xiaomi-a-2026-4k-43-inch-l43mb-aus...,NaN,NaN,NaN,Xiaomi,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
keep_cols = [ 
    "id",
    "name", 
    "image_path", 
    "thumbnail_url", 
    "visible_impression_info_amplitude_category_l1_name"
]

In [5]:
df = df[keep_cols]

In [6]:
rename_dict = {
    "name": "title",
    "image_path": "path",
    "thumbnail_url": "url",
    "visible_impression_info_amplitude_category_l1_name": "category"
}
df = df.rename(columns=rename_dict)

In [7]:
df.head(5)

,id,title,path,url,category
0,278220734,[NEW 2026 TV Series] Smart Tivi Xiaomi TV A Pr...,images/tv/product_278220734.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...,Điện Tử - Điện Lạnh
1,278138258,Smart Tivi LG AI 4K 55 Inch 55UA8450PSA- Hàng ...,images/tv/product_278138258.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...,Điện Tử - Điện Lạnh
2,278138206,Smart Tivi LG AI 4K 65 Inch 65UA8450PSA- Hàng ...,images/tv/product_278138206.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...,Điện Tử - Điện Lạnh
3,278077419,Google Tivi Xiaomi A 2026 4K 55 inch L55MB-ASE...,images/tv/product_278077419.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...,Điện Tử - Điện Lạnh
4,278077327,Google Tivi Xiaomi A 2026 4K 43 inch L43MB-AUS...,images/tv/product_278077327.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...,Điện Tử - Điện Lạnh

In [8]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        100 non-null    int64
 1   title     100 non-null    object
 2   path      100 non-null    object
 3   url       100 non-null    object
 4   category  100 non-null    object
dtypes: int64(1), object(4)
memory usage: 4.0+ KB

                 id
count  1.000000e+02
mean   2.534201e+08
std    5.662742e+07
min    2.003079e+06
25%    2.748706e+08
50%    2.756033e+08
75%    2.768611e+08
max    2.782207e+08

In [9]:
df.isnull().sum().sum()

np.int64(0)

In [10]:
df.isna().sum().sum()

np.int64(0)

In [11]:
df.to_excel("../data_cleaned/tv.xlsx", index=False)