In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import unicodedata

In [2]:
df = pd.read_excel("../../crawl_data/data/data_camera.xlsx")

In [3]:
df.head()

,id,sku,name,url_key,url_path,type,author_name,book_cover,brand_name,short_description,...,badges_new_6_arr_text_0_value,badges_new_6_code,badges_new_6_placement,badges_new_6_text_color,badges_new_6_type,badges_new_4_images_0_image_height,badges_new_4_images_0_image_url,badges_new_4_images_0_image_width,badges_new_5_arr_text_1_value,visible_impression_info_amplitude_gift_rule_ids
0,277854019,8795204295382,Đồng hồ đo Áp suất lốp Ô tô,dong-ho-do-ap-suat-lop-o-to-p277854019,dong-ho-do-ap-suat-lop-o-to-p277854019.html?sp...,NaN,NaN,NaN,OEM,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,277601288,5980799827064,Camera wifi Yoosee Ngoài Trời 20MPX 4 Mắt 3 Mà...,camera-wifi-yoosee-ngoai-troi-20mpx-4-mat-3-ma...,camera-wifi-yoosee-ngoai-troi-20mpx-4-mat-3-ma...,NaN,NaN,NaN,Yoosee,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,277417151,3367749795649,Camera Yoosee Wifi Ngoài Trời 2 Mắt Xem Cùng L...,camera-yoosee-wifi-ngoai-troi-2-mat-xem-cung-l...,camera-yoosee-wifi-ngoai-troi-2-mat-xem-cung-l...,NaN,NaN,NaN,Yoosee,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,277015260,7607448837870,Pin Dành Cho Máy Ảnh Nikon EN-EL14 1500mAh Cao...,pin-danh-cho-may-anh-nikon-en-el14-1500mah-cao...,pin-danh-cho-may-anh-nikon-en-el14-1500mah-cao...,NaN,NaN,NaN,ROGTZ,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,276857147,1981200159179,"Thẻ Vietmap Live Pro Chính Hãng 2025, cảnh báo...",the-vietmap-live-pro-chinh-hang-2025-canh-bao-...,the-vietmap-live-pro-chinh-hang-2025-canh-bao-...,NaN,NaN,NaN,VietMap,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
keep_cols = [ 
    "id",
    "name", 
    "image_path", 
    "thumbnail_url", 
    "visible_impression_info_amplitude_category_l1_name"
]

In [5]:
df = df[keep_cols]

In [6]:
rename_dict = {
    "name": "title",
    "image_path": "path",
    "thumbnail_url": "url",
    "visible_impression_info_amplitude_category_l1_name": "category"
}
df = df.rename(columns=rename_dict)

In [7]:
df.head(5)

,id,title,path,url,category
0,277854019,Đồng hồ đo Áp suất lốp Ô tô,images/camera/277854019.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...,Máy Ảnh - Máy Quay Phim
1,277601288,Camera wifi Yoosee Ngoài Trời 20MPX 4 Mắt 3 Mà...,images/camera/277601288.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...,Máy Ảnh - Máy Quay Phim
2,277417151,Camera Yoosee Wifi Ngoài Trời 2 Mắt Xem Cùng L...,images/camera/277417151.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...,Máy Ảnh - Máy Quay Phim
3,277015260,Pin Dành Cho Máy Ảnh Nikon EN-EL14 1500mAh Cao...,images/camera/277015260.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...,Máy Ảnh - Máy Quay Phim
4,276857147,"Thẻ Vietmap Live Pro Chính Hãng 2025, cảnh báo...",images/camera/276857147.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...,Máy Ảnh - Máy Quay Phim

In [8]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        100 non-null    int64
 1   title     100 non-null    object
 2   path      100 non-null    object
 3   url       100 non-null    object
 4   category  100 non-null    object
dtypes: int64(1), object(4)
memory usage: 4.0+ KB

                 id
count  1.000000e+02
mean   2.150549e+08
std    8.631726e+07
min    4.688897e+06
25%    1.793600e+08
50%    2.709771e+08
75%    2.752751e+08
max    2.779654e+08

In [9]:
df.isnull().sum().sum()

np.int64(0)

In [10]:
df.isna().sum().sum()

np.int64(0)

In [11]:
df.to_excel("../data_cleaned/camera.xlsx", index=False)