In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import unicodedata

In [2]:
df = pd.read_excel("../../crawl_data/data/data_speaker.xlsx")

In [3]:
df.head()

,id,sku,name,url_key,url_path,type,author_name,book_cover,brand_name,short_description,...,badges_new_6_code,badges_new_6_placement,badges_new_6_text_color,badges_new_6_type,badges_new_4_arr_text_1_value,badges_new_4_promotions_1_icon,badges_new_4_promotions_1_icon_height,badges_new_4_promotions_1_icon_width,badges_new_4_promotions_1_text,visible_impression_info_amplitude_combo_deal_id
0,277980303,4750768275106,Loa Momo thông báo chuyển khoản - Tặng khay QR...,loa-momo-thong-bao-chuyen-khoan-tang-khay-qrco...,loa-momo-thong-bao-chuyen-khoan-tang-khay-qrco...,NaN,NaN,NaN,Momo,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,277820438,6626294220372,Loa Bluetooth JBL Charge 6 - Hàng chính hãng,loa-bluetooth-jbl-charge-6-hang-chinh-hang-p27...,loa-bluetooth-jbl-charge-6-hang-chinh-hang-p27...,NaN,NaN,NaN,JBL,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,277615987,5303786037377,Loa Bluetooth ngoài trời Xiaomi BHR4802GL | Ch...,loa-bluetooth-ngoai-troi-xiaomi-bhr4802gl-chon...,loa-bluetooth-ngoai-troi-xiaomi-bhr4802gl-chon...,NaN,NaN,NaN,Xiaomi,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,277548884,1400365236556,Loa vi tính để bàn SUPER BASS cực đã dòng loa ...,loa-vi-tinh-de-ban-super-bass-cuc-da-dong-loa-...,loa-vi-tinh-de-ban-super-bass-cuc-da-dong-loa-...,NaN,NaN,NaN,LuckyJQR,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,277468981,5932807198908,"Loa Bluetooth Mini Karaoke Không Dây, Kèm 2 Mi...",loa-bluetooth-mini-karaoke-khong-day-kem-2-mic...,loa-bluetooth-mini-karaoke-khong-day-kem-2-mic...,NaN,NaN,NaN,MINIIN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
keep_cols = [ 
    "id",
    "name", 
    "image_path", 
    "thumbnail_url", 
    "visible_impression_info_amplitude_category_l1_name"
]

In [5]:
df = df[keep_cols]

In [6]:
rename_dict = {
    "name": "title",
    "image_path": "path",
    "thumbnail_url": "url",
    "visible_impression_info_amplitude_category_l1_name": "category"
}
df = df.rename(columns=rename_dict)

In [7]:
df.head(5)

,id,title,path,url,category
0,277980303,Loa Momo thông báo chuyển khoản - Tặng khay QR...,images/speaker/product_277980303.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...,Thiết Bị Số - Phụ Kiện Số
1,277820438,Loa Bluetooth JBL Charge 6 - Hàng chính hãng,images/speaker/product_277820438.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...,Thiết Bị Số - Phụ Kiện Số
2,277615987,Loa Bluetooth ngoài trời Xiaomi BHR4802GL | Ch...,images/speaker/product_277615987.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...,Thiết Bị Số - Phụ Kiện Số
3,277548884,Loa vi tính để bàn SUPER BASS cực đã dòng loa ...,images/speaker/product_277548884.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...,Thiết Bị Số - Phụ Kiện Số
4,277468981,"Loa Bluetooth Mini Karaoke Không Dây, Kèm 2 Mi...",images/speaker/product_277468981.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...,Thiết Bị Số - Phụ Kiện Số

In [8]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        100 non-null    int64
 1   title     100 non-null    object
 2   path      100 non-null    object
 3   url       100 non-null    object
 4   category  100 non-null    object
dtypes: int64(1), object(4)
memory usage: 4.0+ KB

                 id
count  1.000000e+02
mean   1.942895e+08
std    9.489663e+07
min    1.041800e+05
25%    1.052515e+08
50%    2.526770e+08
75%    2.760534e+08
max    2.781497e+08

In [9]:
df.isnull().sum().sum()

np.int64(0)

In [10]:
df.isna().sum().sum()

np.int64(0)

In [11]:
df.to_excel("../data_cleaned/speaker.xlsx", index=False)