In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import unicodedata

In [2]:
df = pd.read_excel("../../crawl_data/data/data_phone.xlsx")

In [3]:
df.head()

,id,sku,name,url_key,url_path,type,author_name,book_cover,brand_name,short_description,...,badges_new_7_images_0_image_width,badges_new_7_text,badges_new_8_arr_text_0_value,badges_new_8_arr_text_1_value,badges_new_8_code,badges_new_8_placement,badges_new_8_text_color,badges_new_8_type,quantity_sold,badges_new_6_arr_text_1_value
0,278237932,5930715677100,Điện thoại Xiaomi Redmi 14C - Hàng chính hãng,dien-thoai-xiaomi-redmi-14c-hang-chinh-hang-p2...,dien-thoai-xiaomi-redmi-14c-hang-chinh-hang-p2...,NaN,NaN,NaN,Xiaomi,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,278098703,2347132350953,Điện thoại POCO C75 (8GB/256GB) - Hàng Chính Hãng,dien-thoai-poco-c75-8gb-256gb-hang-chinh-hang-...,dien-thoai-poco-c75-8gb-256gb-hang-chinh-hang-...,NaN,NaN,NaN,POCO,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,278000720,6457781969624,Điện thoại HONOR X5b Plus 4GB/128GB - Hàng chí...,dien-thoai-honor-x5b-plus-4gb-128gb-hang-chinh...,dien-thoai-honor-x5b-plus-4gb-128gb-hang-chinh...,NaN,NaN,NaN,Honor,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,277930407,8695120714637,Điện thoại Tecno Spark GO 1 (3GB/64GB) - Hàng ...,dien-thoai-tecno-spark-go-1-3gb-64gb-hang-chin...,dien-thoai-tecno-spark-go-1-3gb-64gb-hang-chin...,NaN,NaN,NaN,Tecno,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,277777809,3255173313774,"Điện thoại Samsung Galaxy A26 5G (8/128GB), Mặ...",dien-thoai-samsung-galaxy-a26-5g-8-128gb-mat-l...,dien-thoai-samsung-galaxy-a26-5g-8-128gb-mat-l...,NaN,NaN,NaN,Samsung,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
keep_cols = [ 
    "name", 
    "image_path", 
    "thumbnail_url"
]

In [5]:
df = df[keep_cols]

In [6]:
rename_dict = {
    "name": "title",
    "image_path": "path",
    "thumbnail_url": "url"
}
df = df.rename(columns=rename_dict)

In [7]:
df.head(5)

,title,path,url
0,Điện thoại Xiaomi Redmi 14C - Hàng chính hãng,images/phone/278237932.png,https://salt.tikicdn.com/cache/280x280/ts/prod...
1,Điện thoại POCO C75 (8GB/256GB) - Hàng Chính Hãng,images/phone/278098703.png,https://salt.tikicdn.com/cache/280x280/ts/prod...
2,Điện thoại HONOR X5b Plus 4GB/128GB - Hàng chí...,images/phone/278000720.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...
3,Điện thoại Tecno Spark GO 1 (3GB/64GB) - Hàng ...,images/phone/277930407.png,https://salt.tikicdn.com/cache/280x280/ts/prod...
4,"Điện thoại Samsung Galaxy A26 5G (8/128GB), Mặ...",images/phone/277777809.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...

In [8]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   title   100 non-null    object
 1   path    100 non-null    object
 2   url     100 non-null    object
dtypes: object(3)
memory usage: 2.5+ KB

,title,path,url
count,100,100,100
unique,99,100,100
top,Điện Thoại Oppo A58 6GB/128GB - Hàng Chính Hãng,images/phone/278237932.png,https://salt.tikicdn.com/cache/280x280/ts/prod...
freq,2,1,1

In [9]:
df.isnull().sum().sum()

np.int64(0)

In [10]:
df.isna().sum().sum()

np.int64(0)

In [11]:
df.to_excel("../data_cleaned/phone.xlsx", index=False)