In [46]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import unicodedata

In [47]:
df = pd.read_excel("../../crawl_data/data/data_phone.xlsx")

In [48]:
df.head()

,id,sku,name,url_key,url_path,type,author_name,book_cover,brand_name,short_description,...,badges_new_7_text,badges_new_8_arr_text_0_value,badges_new_8_code,badges_new_8_placement,badges_new_8_text_color,badges_new_8_type,visible_impression_info_amplitude_discounted_by_rule_ids,badges_new_8_arr_text_1_value,badges_new_6_arr_text_1_value,quantity_sold
0,278237932,5930715677100,Điện thoại Xiaomi Redmi 14C - Hàng chính hãng,dien-thoai-xiaomi-redmi-14c-hang-chinh-hang-p2...,dien-thoai-xiaomi-redmi-14c-hang-chinh-hang-p2...,NaN,NaN,NaN,Xiaomi,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,278098703,5570280517992,Điện thoại POCO C75 (8GB/256GB) - Hàng Chính Hãng,dien-thoai-poco-c75-8gb-256gb-hang-chinh-hang-...,dien-thoai-poco-c75-8gb-256gb-hang-chinh-hang-...,NaN,NaN,NaN,POCO,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,278000720,6457781969624,Điện thoại HONOR X5b Plus 4GB/128GB - Hàng chí...,dien-thoai-honor-x5b-plus-4gb-128gb-hang-chinh...,dien-thoai-honor-x5b-plus-4gb-128gb-hang-chinh...,NaN,NaN,NaN,Honor,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,277930407,8695120714637,Điện thoại Tecno Spark GO 1 (3GB/64GB) - Hàng ...,dien-thoai-tecno-spark-go-1-3gb-64gb-hang-chin...,dien-thoai-tecno-spark-go-1-3gb-64gb-hang-chin...,NaN,NaN,NaN,Tecno,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,277777809,4865918741583,"Điện thoại Samsung Galaxy A26 5G (8/128GB), Mặ...",dien-thoai-samsung-galaxy-a26-5g-8-128gb-mat-l...,dien-thoai-samsung-galaxy-a26-5g-8-128gb-mat-l...,NaN,NaN,NaN,Samsung,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [49]:
keep_cols = [ 
    "id",
    "name", 
    "image_path", 
    "thumbnail_url", 
    "visible_impression_info_amplitude_category_l1_name"
]

In [50]:
df = df[keep_cols]

In [51]:
rename_dict = {
    "name": "title",
    "visible_impression_info_amplitude_category_l1_name": "category"
}
df = df.rename(columns=rename_dict)

In [52]:
df

,id,title,image_path,thumbnail_url,category
0,278237932,Điện thoại Xiaomi Redmi 14C - Hàng chính hãng,images/phone/product_278237932.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...,Điện Thoại - Máy Tính Bảng
1,278098703,Điện thoại POCO C75 (8GB/256GB) - Hàng Chính Hãng,images/phone/product_278098703.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...,Điện Thoại - Máy Tính Bảng
2,278000720,Điện thoại HONOR X5b Plus 4GB/128GB - Hàng chí...,images/phone/product_278000720.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...,Điện Thoại - Máy Tính Bảng
3,277930407,Điện thoại Tecno Spark GO 1 (3GB/64GB) - Hàng ...,images/phone/product_277930407.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...,Điện Thoại - Máy Tính Bảng
4,277777809,"Điện thoại Samsung Galaxy A26 5G (8/128GB), Mặ...",images/phone/product_277777809.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...,Điện Thoại - Máy Tính Bảng
...,...,...,...,...,...
95,276500230,Máy đọc sách Kindle Colorsoft Signature Editio...,images/phone/product_276500230.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...,Điện Thoại - Máy Tính Bảng
96,276489194,Điện thoại Samsung Galaxy S24 FE - Hàng chính ...,images/phone/product_276489194.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...,Điện Thoại - Máy Tính Bảng
97,276465090,Combo Máy đọc sách Amazon Kindle Paperwhite 6 ...,images/phone/product_276465090.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...,Điện Thoại - Máy Tính Bảng
98,276099688,"Xiaomi Redmi Note 12 5G 8GB/128GB ,Màn AMOLED ...",images/phone/product_276099688.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...,Điện Thoại - Máy Tính Bảng
99,276062770,Điện Thoại Xiaomi Redmi 14C 4GB/128GB - Hàng C...,images/phone/product_276062770.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...,Điện Thoại - Máy Tính Bảng

In [53]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             100 non-null    int64
 1   title          100 non-null    object
 2   image_path     100 non-null    object
 3   thumbnail_url  100 non-null    object
 4   category       100 non-null    object
dtypes: int64(1), object(4)
memory usage: 4.0+ KB

                 id
count  1.000000e+02
mean   2.582560e+08
std    4.806957e+07
min    1.125177e+07
25%    2.743521e+08
50%    2.765772e+08
75%    2.774447e+08
max    2.782379e+08

In [54]:
df.isnull().sum().sum()

np.int64(0)

In [55]:
df.isna().sum().sum()

np.int64(0)

In [56]:
df.to_excel("../data_cleaned/phone.xlsx", index=False)