In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import unicodedata

In [2]:
df = pd.read_excel("../../crawl_data/data/data_laptop.xlsx")

In [3]:
df.head()

,id,sku,name,url_key,url_path,type,author_name,book_cover,brand_name,short_description,...,badges_new_6_type,visible_impression_info_amplitude_gift_rule_ids,badges_new_3_icon,badges_new_3_icon_height,badges_new_3_icon_width,badges_new_2_icon,badges_new_2_icon_height,badges_new_2_icon_width,badges_new_3_arr_text_0_value,badges_new_4_arr_text_0_value
0,278226869,2945221924243,Laptop Dell Inspiron 3530 71043887( Core i5-13...,laptop-dell-inspiron-3530-71043887-core-i5-133...,laptop-dell-inspiron-3530-71043887-core-i5-133...,NaN,NaN,NaN,Dell,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,278226504,8916945952669,Laptop Dell Inspiron 15 3530 N3530-i3U085W11SL...,laptop-dell-inspiron-15-3530-n3530-i3u085w11sl...,laptop-dell-inspiron-15-3530-n3530-i3u085w11sl...,NaN,NaN,NaN,Dell,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,278078317,3260486333768,Asus Vivobook S 14 Flip TP3402VA-LZ632W (Intel...,asus-vivobook-s-14-flip-tp3402va-lz632w-intel-...,asus-vivobook-s-14-flip-tp3402va-lz632w-intel-...,NaN,NaN,NaN,Asus,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,278078298,4377873239825,Asus Vivobook 15 X1502VA-BQ886W (Intel Core i7...,asus-vivobook-15-x1502va-bq886w-intel-core-i7-...,asus-vivobook-15-x1502va-bq886w-intel-core-i7-...,NaN,NaN,NaN,Asus,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,278078286,8288406691059,Asus Vivobook 14 X1405VA-LY623W (Intel Core i5...,asus-vivobook-14-x1405va-ly623w-intel-core-i5-...,asus-vivobook-14-x1405va-ly623w-intel-core-i5-...,NaN,NaN,NaN,Asus,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
keep_cols = [ 
    "id",
    "name", 
    "image_path", 
    "thumbnail_url", 
    "visible_impression_info_amplitude_category_l1_name"
]

In [5]:
df = df[keep_cols]

In [6]:
rename_dict = {
    "name": "title",
    "image_path": "path",
    "thumbnail_url": "url",
    "visible_impression_info_amplitude_category_l1_name": "category"
}
df = df.rename(columns=rename_dict)

In [7]:
df.head(5)

,id,title,path,url,category
0,278226869,Laptop Dell Inspiron 3530 71043887( Core i5-13...,images/laptop/product_278226869.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...,Laptop - Máy Vi Tính - Linh kiện
1,278226504,Laptop Dell Inspiron 15 3530 N3530-i3U085W11SL...,images/laptop/product_278226504.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...,Laptop - Máy Vi Tính - Linh kiện
2,278078317,Asus Vivobook S 14 Flip TP3402VA-LZ632W (Intel...,images/laptop/product_278078317.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...,Laptop - Máy Vi Tính - Linh kiện
3,278078298,Asus Vivobook 15 X1502VA-BQ886W (Intel Core i7...,images/laptop/product_278078298.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...,Laptop - Máy Vi Tính - Linh kiện
4,278078286,Asus Vivobook 14 X1405VA-LY623W (Intel Core i5...,images/laptop/product_278078286.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...,Laptop - Máy Vi Tính - Linh kiện

In [8]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        100 non-null    int64
 1   title     100 non-null    object
 2   path      100 non-null    object
 3   url       100 non-null    object
 4   category  100 non-null    object
dtypes: int64(1), object(4)
memory usage: 4.0+ KB

                 id
count  1.000000e+02
mean   2.527973e+08
std    4.384160e+07
min    6.798288e+07
25%    2.422272e+08
50%    2.757983e+08
75%    2.779127e+08
max    2.784547e+08

In [9]:
df.isnull().sum().sum()

np.int64(0)

In [10]:
df.isna().sum().sum()

np.int64(0)

In [11]:
df.to_excel("../data_cleaned/laptop.xlsx", index=False)