In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import unicodedata

In [2]:
df = pd.read_excel("../../crawl_data/data/data_tv.xlsx")

In [3]:
df.head()

,id,sku,name,url_key,url_path,type,author_name,book_cover,brand_name,short_description,...,badges_new_4_arr_text_0_value,badges_new_4_text_color,badges_new_4_icon,badges_new_4_icon_height,badges_new_4_icon_width,badges_new_3_promotions_0_icon,badges_new_3_promotions_0_icon_height,badges_new_3_promotions_0_icon_width,badges_new_3_promotions_0_text,visible_impression_info_amplitude_ineligible_coupon_rule_id
0,278220734,2004742899164,[NEW 2026 TV Series] Smart Tivi Xiaomi TV A Pr...,new-2026-tv-series-smart-tivi-xiaomi-tv-a-pro-...,new-2026-tv-series-smart-tivi-xiaomi-tv-a-pro-...,NaN,NaN,NaN,Xiaomi,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,278138258,5502954751332,Smart Tivi LG AI 4K 55 Inch 55UA8450PSA- Hàng ...,smart-tivi-lg-ai-4k-55-inch-55ua8450psa-hang-c...,smart-tivi-lg-ai-4k-55-inch-55ua8450psa-hang-c...,NaN,NaN,NaN,LG,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,278077419,1516540466887,Google Tivi Xiaomi A 2026 4K 55 inch L55MB-ASE...,google-tivi-xiaomi-a-2026-4k-55-inch-l55mb-ase...,google-tivi-xiaomi-a-2026-4k-55-inch-l55mb-ase...,NaN,NaN,NaN,Xiaomi,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,278077327,2768528301218,Google Tivi Xiaomi A 2026 4K 43 inch L43MB-AUS...,google-tivi-xiaomi-a-2026-4k-43-inch-l43mb-aus...,google-tivi-xiaomi-a-2026-4k-43-inch-l43mb-aus...,NaN,NaN,NaN,Xiaomi,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,278009387,8760632727779,Google Tivi Coocaa Full. HD 43 inch 43Z73 - h...,google-tivi-coocaa-full-hd-43-inch-43z73-p2780...,google-tivi-coocaa-full-hd-43-inch-43z73-p2780...,NaN,NaN,NaN,coocaa,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
keep_cols = [ 
    "name", 
    "image_path", 
    "thumbnail_url"
]

In [5]:
df = df[keep_cols]

In [6]:
rename_dict = {
    "name": "title",
    "image_path": "path",
    "thumbnail_url": "url"
}
df = df.rename(columns=rename_dict)

In [7]:
df.head(5)

,title,path,url
0,[NEW 2026 TV Series] Smart Tivi Xiaomi TV A Pr...,images/tv/278220734.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...
1,Smart Tivi LG AI 4K 55 Inch 55UA8450PSA- Hàng ...,images/tv/278138258.png,https://salt.tikicdn.com/cache/280x280/ts/prod...
2,Google Tivi Xiaomi A 2026 4K 55 inch L55MB-ASE...,images/tv/278077419.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...
3,Google Tivi Xiaomi A 2026 4K 43 inch L43MB-AUS...,images/tv/278077327.png,https://salt.tikicdn.com/cache/280x280/ts/prod...
4,Google Tivi Coocaa Full. HD 43 inch 43Z73 - h...,images/tv/278009387.png,https://salt.tikicdn.com/cache/280x280/ts/prod...

In [8]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   title   100 non-null    object
 1   path    100 non-null    object
 2   url     100 non-null    object
dtypes: object(3)
memory usage: 2.5+ KB

,title,path,url
count,100,100,100
unique,100,100,100
top,[NEW 2026 TV Series] Smart Tivi Xiaomi TV A Pr...,images/tv/278220734.jpg,https://salt.tikicdn.com/cache/280x280/ts/prod...
freq,1,1,1

In [9]:
df.isnull().sum().sum()

0

In [10]:
df.isna().sum().sum()

0

In [11]:
df.to_excel("../data_cleaned/tv.xlsx", index=False)